import type { Metadata } from "next";
import { Playfair_Display, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const headingFont = Playfair_Display({
    variable: "--font-playfair",
    subsets: ["latin"],
});

const secondaryFont = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Lumea Medical Spa Animations by Motion",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${headingFont.variable} ${secondaryFont.variable} antialiased`}
            >
                <Navbar />
                {children}
            </body>
        </html>
    );
}
